apiVersion: v1
kind: Service
metadata:
  namespace: confluent
  name: kafka-localhost
spec:
  type: LoadBalancer
  selector:
    app: kafka
    type: kafka
  ports:
    - name: external
      port: 9092
      targetPort: 9092

