apiVersion: v1
kind: Service
metadata:
  namespace: confluent
  name: schemaregistry-localhost
spec:
  type: LoadBalancer
  selector:
    app: schemaregistry
    type: schemaregistry
  ports:
    - name: external
      port: 8081
      targetPort: 8081

